Your.order
katerynakyryliuk2024/LogicLions pull request #1
Opened 2024-05-25 10:25 UTC by olha12melnychuk

Пробна версія пулреквесту))

2024-05-25 11:12 UTC, katerynakyryliuk2024 commented on src/css/section-your-order.css
> +.accent {
огорни  в span жовту частину тексту. так як білтй колір є кольором body.

2024-05-25 11:32 UTC, katerynakyryliuk2024 requested changes
Оля ти молодець)))) ми з другою Ольою тестували твій реквест. І не знайшли твій спрайт, бо svg стрілочку не видно.

2024-05-25 11:32 UTC, katerynakyryliuk2024 commented on src/css/section-your-order.css
> +.form-field-wraper {
давай добавимо замість div , form щоб він огортав label.

2024-05-25 11:32 UTC, katerynakyryliuk2024 commented on src/css/section-your-order.css
> +.accent {
огорни в span жовту частину тексту. так як білтй колір є кольором body.

2024-05-26 06:01 UTC, olha12melnychuk commented
Внесла зміни згідно коментів

2024-05-26 06:01 UTC, closed without merging